import { getStore } from "@netlify/blobs";
import type { Config, Context } from "@netlify/functions";
const COLS=new Set(['config','members','tx','rec','shop','hist','inv','goals','contrib','settle','meals']);
const ID_RE=/^[A-Za-z0-9_\-.:]{1,80}$/;const MAX_BODY=64*1024;const st=()=>getStore('futari-kakeibo',{consistency:'strong'});
const json=(o:unknown,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});const err=(c:string,s:number)=>json({error:c},s);
async function sha256(x:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function newKey(){return Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url')}
function seq(){return Date.now()*1000+Math.floor(Math.random()*1000)}
async function auth(req:Request){const h=req.headers.get('Authorization')||'',k=h.startsWith('Bearer ')?h.slice(7).trim():'';if(!/^[A-Za-z0-9_-]{40,60}$/.test(k))return null;const hash=await sha256(k),hid=await st().get(`auth:${hash}`,{type:'text'});return hid?{hid:String(hid),hash}:null}
async function body(req:Request){const t=await req.text();if(t.length>MAX_BODY)return null;try{const v=JSON.parse(t);return v&&typeof v==='object'&&!Array.isArray(v)?v:null}catch{return null}}
export default async(req:Request,ctx:Context)=>{const u=new URL(req.url),p=u.pathname,s=st();try{if(req.method!=='GET'){const o=req.headers.get('Origin');if(o&&o!==u.origin)return err('forbidden',403)}if(p==='/api/households'&&req.method==='POST'){const key=newKey(),hid=crypto.randomUUID(),hash=await sha256(key);await s.set(`auth:${hash}`,hid);await s.setJSON(`household:${hid}`,{createdAt:Date.now()});return json({key})}const a=await auth(req);if(!a)return err('unauthorized',401);const hid=a.hid;if(p==='/api/sync'&&req.method==='GET'){const since=Math.max(0,Number(u.searchParams.get('since'))||0),l=await s.list({prefix:`doc:${hid}:`}),docs:any[]=[];for(const b of l.blobs){const r:any=await s.get(b.key,{type:'json'});if(r&&Number(r.seq)>since)docs.push({col:r.col,id:r.id,seq:r.seq,deleted:!!r.deleted,data:r.deleted?null:r.data})}docs.sort((x,y)=>x.seq-y.seq);const pg=docs.slice(0,1000);return json({docs:pg,cursor:pg.length?pg[pg.length-1].seq:since,more:docs.length>1000})}if(p==='/api/doc'){const col=u.searchParams.get('col'),id=u.searchParams.get('id');if(!col||!COLS.has(col)||!ID_RE.test(id||''))return err('invalid_argument',400);const k=`doc:${hid}:${col}:${id}`;if(req.method==='GET'){const r:any=await s.get(k,{type:'json'});return json(r&&!r.deleted?{exists:true,data:r.data,seq:r.seq}:{exists:false})}if(req.method==='PUT'){const d=await body(req);if(d===null)return err('invalid_argument',400);const old:any=await s.get(k,{type:'json'});if(u.searchParams.get('create')==='1'&&old&&!old.deleted)return err('already_exists',409);const q=seq();await s.setJSON(k,{col,id,data:d,seq:q,deleted:false});return json({ok:true,seq:q})}if(req.method==='DELETE'){const old:any=await s.get(k,{type:'json'}),q=seq();await s.setJSON(k,{col,id,data:null,seq:q,deleted:true});return json({ok:true,changed:old&&!old.deleted?1:0})}}if(p==='/api/rotate'&&req.method==='POST'){const key=newKey(),hash=await sha256(key);await s.set(`auth:${hash}`,hid);await s.delete(`auth:${a.hash}`);return json({key})}return err('not_found',404)}catch(e){console.error(e);return err('unavailable',500)}};
export const config:Config={path:'/api/*'};
